-- Auto-generated from schema-map-postgres.psd1 (map@9d3471b)
-- engine: postgres
-- table:  cart_items
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id CHAR(36) NOT NULL,
  book_id BIGINT NOT NULL,
  sku VARCHAR(64) NULL,
  variant JSONB NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  price_snapshot NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  meta JSONB NULL,
  CONSTRAINT chk_cart_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_cart_qty CHECK (quantity > 0)
);
